Add dialog
devonfw-sample/basic-flutter pull request #45
Opened 2021-12-30 14:14 UTC by TugbaDalmaz

2021-12-30 15:27 UTC, HKayed requested changes

2021-12-30 15:27 UTC, HKayed commented on basic_flutter/lib/data/employee.dart
> +  });
I believe it would be convenient if you add firstName and id because then we would be able to get the response from the server on the update

2022-01-04 11:03 UTC, HKayed approved these changes

2022-01-05 20:25 UTC, nicotheod requested changes
Most of the code would be fine if you want to make a small app with StatefulWidgets as the state management, but here we are using bloc for it and using best practices.  With that there will be a lot of changes needed.

2022-01-24 15:56 UTC, closed without merging